---
- name: Deploy Home Assistant MCP Server container
  hosts: moginsok.dumont-lab.lan
  vars_files:
    - secrets_folder/ha-token

  vars:
    podman_run_as_user: container-user

  tasks:
    - name: Apply quadlet
      include_role:
        name: redhat.rhel_system_roles.podman
      vars:
        podman_run_as_user: container-user
        podman_quadlet_specs:
          - name: ha-mcp
            type: container
            state: started
            file_content: |
              [Unit]
              Description=Home Assistant MCP Server

              [Container]
              ContainerName=ha-mcp
              Image=ghcr.io/homeassistant-ai/ha-mcp:latest
              AutoUpdate=registry
              PublishPort=3500:8086

              Exec=ha-mcp-web

              Environment=HOMEASSISTANT_URL=https://192.168.75.36:8123
              Environment=HOMEASSISTANT_VERIFY_SSL=false
              Environment=HOMEASSISTANT_TOKEN={{ ha_long_lived_token }}
              Environment=MCP_PORT=8086
              Environment=PYTHONUNBUFFERED=1
              Volume=ha-mcp-data:/home/mcpuser/.ha-mcp:z

              [Service]
              Restart=always
              RestartSec=5s

              [Install]
              WantedBy=default.target

