---
- name: Deploy Home Assistant MCP Server container
  hosts: n305.dumont-lab.lan
  vars_files:
    - secrets_folder/ha-token

  vars:
    podman_run_as_user: container-user

  tasks:
    - name: Apply quadlet
      include_role:
        name: redhat.rhel_system_roles.podman
      vars:
        podman_run_as_user: container-user
        podman_quadlet_specs:
          - name: ha-mcp
            type: container
            state: started
            file_content: |
              [Unit]
              Description=Home Assistant MCP Server

              [Container]
              ContainerName=ha-mcp
              Image=ghcr.io/homeassistant-ai/ha-mcp:latest
              AutoUpdate=registry
              Exec=fastmcp run fastmcp-sse.json
              PublishPort=3500:8087
              Environment=HOMEASSISTANT_URL=http://192.168.75.36:8123
              Environment=HOMEASSISTANT_TOKEN={{ ha_long_lived_token }}

              [Service]
              Restart=always

              [Install]
              WantedBy=default.target

